FROM python:3.8-slim-buster

COPY python/main.py python/main.py

COPY python/image python/image

copy db ./db

COPY python/requirements.txt python/requirements.txt

WORKDIR /python

RUN pip3 install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
